org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=34

flutter.deferred-components=false

org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configureondemand=true
